"""latest

Revision ID: 5ac8f76d73a4
Revises: 3ecf992722b8
Create Date: 2024-09-02 11:28:08.162947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac8f76d73a4'
down_revision = '3ecf992722b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows_actors',
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], name=op.f('fk_shows_actors_actor_id_actors')),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], name=op.f('fk_shows_actors_show_id_shows')),
    sa.PrimaryKeyConstraint('show_id', 'actor_id')
    )
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('location')

    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), nullable=True))

    op.drop_table('shows_actors')
    # ### end Alembic commands ###
