"""update role field

Revision ID: 6f0a3ad23840
Revises: 992b60fad89c
Create Date: 2024-09-21 14:27:40.657625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0a3ad23840'
down_revision = '992b60fad89c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows_actors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows_actors', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
