"""add showid to actors model

Revision ID: 992b60fad89c
Revises: 55e54362ef6a
Create Date: 2024-09-20 13:23:40.266428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992b60fad89c'
down_revision = '55e54362ef6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_actors_show_id_shows'), 'shows', ['show_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_actors_show_id_shows'), type_='foreignkey')
        batch_op.drop_column('show_id')

    # ### end Alembic commands ###
